### ISSUE TITLE
Projection for shapefile

### ISSUE THREAD

**Issue by denny123** [calvinmetcalf/leaflet.shapefile#13]
I have shp in epsg:4326 with circle, but circle show on leaflet map how ellipse. If i change shape projection on EPSG:3857 my shape not show.

**Comment by calvinmetcalf** [comment]
and you post the original shapefile (with the correct .prj file)?

**Comment by denny123** [comment]
http://speedy.sh/2qVBC/test.zip

**Comment by calvinmetcalf** [comment]
shapefiles don't support circles so what arcgis does is turns them into polygons that are in the shape of the circle, the problem you have is that your shapefile is being reprojected from 4326 to 3857 which is causing it to be an ellipse because in 4326 the units are degrees (which are not the same in the x and y dimensions) while in 3857 the units are meters which are the same.  the shape projection (assuming you mean the .prj file) is descriptive, it describes what the shapefile is using, if you change it manually then it's not that the shapefile won't render, it will just be located [around here](http://www.openstreetmap.org/#map=18/0.00000/0.00000)

solution: convert to 3857 in arcgis (assuming you are using that) and then export to shapefile

**Comment by denny123** [comment]
If i create shape on 3857 in ArcMap in lealet map not show.

**Comment by calvinmetcalf** [comment]
can you post that one?

**Comment by denny123** [comment]
http://www.directlinkupload.com/uploads/195.128.137.26/test_3857.zip

**Comment by calvinmetcalf** [comment]
![screen shot 2014-08-15 at 7 57 03 am](https://cloud.githubusercontent.com/assets/1128607/3932867/52adb978-2473-11e4-9068-21c846c023f8.png)

shows up for me

**Comment by denny123** [comment]
can you show me your script with my shape-layer-3857?

**Comment by calvinmetcalf** [comment]
I drag and dropped the script onto http://leaflet.calvinmetcalf.com

On Fri, Aug 15, 2014 at 8:52 AM, denny123 notifications@github.com wrote:

> can you show me your script with my shape-layer-3857?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/calvinmetcalf/leaflet.shapefile/issues/13#issuecomment-52302109
> .

## 

-Calvin W. Metcalf

**Comment by denny123** [comment]
i dunno how there, but myscript on standard leafletmap is:(not show)

```
      var test_shp =  new L.Shapefile('/dostup/test_shp/test_3857',{
                    onEachFeature: onEachFeature_test,
                   style: style_test,
      });
```

how there(on this site-upload-layer) show shape? may be set projection anywhere? i not see script leaflet.shpfile.js?

**Comment by denny123** [comment]
May be i need another function(or plugin)?

**Comment by calvinmetcalf** [comment]
if you are able to post some code that works with the first shapefile but
not the second it should work with either and does for me.

On Mon, Aug 18, 2014 at 2:20 AM, denny123 notifications@github.com wrote:

> May be i need another function(or plugin)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/calvinmetcalf/leaflet.shapefile/issues/13#issuecomment-52455941
> .

## 

-Calvin W. Metcalf

**Comment by denny123** [comment]
All codes works, but how correction projection for standard leaflet map?

**Comment by calvinmetcalf** [comment]
The shapefile plugin takes care of projecting the shapefile, if Savin the
file in a different projection causes things to work differently then there
is  likely a bug somewhere, the fact that the shapefile works some places
(eg http://leaflet.calvinmetcalf.com) makes me wonder if I don't understand
what you're code is doing

**Comment by denny123** [comment]
ok, can you help for set projection on leaflet map EPSG:4326 for my shapefile(L.Shapefile) with projection EPSG:3857?

**Comment by calvinmetcalf** [comment]
can you post on gist.github.com the code you are using to try to display shape-layer-3857 which does not work?

**Comment by denny123** [comment]
http://stackoverflow.com/questions/25357790/not-show-l-geojson-with-proj-epsg3857-on-leaflet-map
ok?(map and layer)

**Comment by calvinmetcalf** [comment]
what are onEachFeature_test and style_test also are the 2 shapefiles you posted supposed to be the same file just saved in different projections? because they look like they have different features.

**Comment by denny123** [comment]
No different, only shapefiles.

```
     function style_test(feature) {
           return {
           fillColor: 'green',
          weight: 2,
          opacity: 1,
         color: 'red',
           dashArray: '3',
          fillOpacity: 1
            };
       }

      function zoomToFeature_test(e) {
                      xmlhttp.open('GET', '/dostup/data_json.php?epsg=shp&str='+e.target.feature.properties.test, false);
                      xmlhttp.send(null);
                     if(xmlhttp.status == 200) {
                                                  var conv_test = xmlhttp.responseText;
             };

              map.fitBounds(e.target.getBounds());
                   e.target.bindPopup('Mytest: '+conv_test);
              }

             function onEachFeature_test(feature, layer) {
                    layer.on({
                       click: zoomToFeature_test,
                    });
             }
```

**Comment by calvinmetcalf** [comment]
> No different only shalefiles.

I don't understand

**Comment by denny123** [comment]
not show(3857):

```
      var test_shp =  new L.Shapefile('/dostup/test_shp/test_3857',{
                              onEachFeature: onEachFeature_test,
                               style: style_test,
           });
```

and layer show(4326):

```
        var test_shp =  new L.Shapefile('/dostup/test_shp/test_portal',{
                                 onEachFeature: onEachFeature_test,
                                 style: style_test,
         });
```

**Comment by calvinmetcalf** [comment]
and the shapefiles, the 2 that you send me look like they are of different things

**Comment by denny123** [comment]
yes thay are different things and projection. I create new 4326 and new 3857. But both create in ArcMap.

**Comment by calvinmetcalf** [comment]
ok

**Comment by denny123** [comment]
I tried convert projection and i do 2 commands:

```
 npm install -g browserify
 npm install -g reproject
```

and after this commands my shapelayer-3857 was showing on map. I dunno why, you know?

but with another plugin(shapefile-js)(this now show):

```
      var test_shp =  new L.geoJson({features:[]},{
                  onEachFeature: onEachFeature_test,
                  style: style_test,
     });

     shp("/dostup/test_shp/test_3857").then(function(data){
                test_shp.addData(data);
     });
```

**Comment by calvinmetcalf** [comment]
without knowing what exactly your shapefile has I can't solve this, but shapefile-js is used by this plugin maybe this one has an out of date version

**Comment by denny123** [comment]
may be.

**Comment by calvinmetcalf** [comment]
updated the version of shpjs that lives in the repo

**Comment by denny123** [comment]
but leaflet.shapefile.js is not working

**Comment by calvinmetcalf** [comment]
can you be more specific

**Comment by denny123** [comment]
Yes, this is not show:

```
           var test_shp =  new L.Shapefile('/dostup/test_shp/test_3857',{
                     onEachFeature: onEachFeature_test,
                     style: style_test,
           });
```

this is show:

```
          var test_shp =  new L.geoJson({features:[]},{
                      onEachFeature: onEachFeature_test,
                      style: style_test,
          });
          shp("/dostup/test_shp/test_3857").then(function(data){
                     test_shp.addData(data);
          }); 
```

**Comment by calvinmetcalf** [comment]
I took this repo, I put the contents of http://www.directlinkupload.com/uploads/195.128.137.26/test_3857.zip into a folder in the root of the repo called test_3857 and then I changed this line https://github.com/calvinmetcalf/leaflet.shapefile/blob/c3bbcab5a82149b18e2b6a68b2386e88dedab895/index.html#L31 to be 'test_3857/test_3857' instead of 'congress.zip', I then zoomed out and could see a small shape which resolved when I zoomed in.

I don't know what you are doing differently, but it would help if you could open the console log and see if there are any errors.

**Comment by denny123** [comment]
No errors, but very many scripts-codes, i dunno why.
