### ISSUE TITLE
Shapes are not showed

### ISSUE THREAD

**Issue by erisazani** [calvinmetcalf/leaflet.shapefile#19]
Hi Calvin,

I used shapefiles that I got from http://www.geopostcodes.com/Indonesia - sample data. The downloaded data contains not only shapefiles, but also some others. Then I took only the Shapefile folder (containing shp, shx, dbf, and prj), zipped them, and feed L.Shapefile with that (I have performed chmod +x to the zipped file).

However, the shapes are not rendered to the map. And before, I have tried two other shapefiles from http://thematicmapping.org/downloads/world_borders.php and both worked (both are .zip files from the start).

Any thought on this? Thanks!

*Also have posted this question at http://stackoverflow.com/questions/27418105/leaflet-shapefiles-required-to-show-shapes

**Comment by calvinmetcalf** [comment]
looks like there is a bug in the shapefile script involving text decoder

**Comment by calvinmetcalf** [comment]
update looks to be an issue with unzipping

**Comment by calvinmetcalf** [comment]
so for now you can put them in a folder and point the script to the path to the files without the .shp/.dbf/.prj extention

**Comment by calvinmetcalf** [comment]
update your copy of shapefilejs and it should work

**Comment by erisazani** [comment]
Hi Calvin,

It seems that my guess was right, I tried zipping them via zip command from shell instead of compressing via finder->right click, and it worked.
