### ISSUE TITLE
shape file is not loading

### ISSUE THREAD

**Issue by abdulrehmanch** [calvinmetcalf/leaflet.shapefile#20]
I got this error while i am trying to load shp file on local host.
 GET http://localhost/WEBGIS/shp.js 404 (Not Found)

unexpectedly the same code working fine online. 

some body help me to find out the solution...plzzz

**Comment by calvinmetcalf** [comment]
you are probably missing the port number, but this isn't really an issue with the library as much as your sever set up

**Comment by abdulrehmanch** [comment]
but my server is iis and doesnt need port no i think. isn't it?

**Comment by calvinmetcalf** [comment]
I don't have any experience with IIS sorry.
