### ISSUE TITLE
Demo hangs on mac with updated chrome, firefox, and safari.

### ISSUE THREAD

**Issue by davidlukerice** [calvinmetcalf/leaflet.shapefile#24]
Was having some trouble loading larger shape files in my application (~10mb), so went back to see if they loaded alright in the [linked to demo](http://calvinmetcalf.github.io/leaflet.shapefile/). When loading the page, though, it now hangs for me on chrome, firefox, and safari. On firefox, the initial leaflet map loads but get a `warning: Unresponsive script` for `http://calvinmetcalf.github.io/leaflet.shapefile/catiline.js:255`

Mac osx 10.10.3
Chrome 43.0.2357.65 (64-bit)
Firefox 38.0.1
Safari 8.0.6 (10600.6.3)

**Comment by calvinmetcalf** [comment]
er woops recent ability to specify script location broke how it works in a worker, pushing up a fix

**Comment by davidlukerice** [comment]
Guess I'm the one who broke it then, sorry. How does [changing it over to a `new Function`](https://github.com/calvinmetcalf/leaflet.shapefile/commit/478969ab55ea49542a30f382904d386296e82f4a) fix it? Was the issue trying to access the `importUrl` variable inside the worker function?

**Comment by calvinmetcalf** [comment]
yeah it expects a string to be there not a variable

**Comment by davidlukerice** [comment]
Awesome. Everything's working again for me so I'll go ahead and close the issue. Thanks so much for the quick fix.
