### ISSUE TITLE
Popup information not showing

### ISSUE THREAD

**Issue by ghost** [calvinmetcalf/leaflet.shapefile#25]
Hello, thanks for writing this plugin!

I'm having an issue with getting popup information to show up. I loaded a zipped shapefile into an arraybuffer and create a new shapefile like so:

var layer = new L.Shapefile(r.result, {style: {
                                    "color": "#000000",
                                    "fill": "none",
                                    "weight": 2,
                                    "opacity": .9
                                }}).addTo(leafletMainMap);

It shows up on the map, but when I click on a marker, there is no popup.  I tried looking through http://leaflet.calvinmetcalf.com/script.js, but I couldn't find the code that creates the popup.  I'm not using the web workers/catiline to do this.  Any ideas?

**Comment by calvinmetcalf** [comment]
it works just like the leaflet [geojson layer](http://leafletjs.com/reference.html#geojson) so you have to explicitly create the popup, which is done [here](https://github.com/calvinmetcalf/leaflet.shapefile/blob/478969ab55ea49542a30f382904d386296e82f4a/index.html#L33)

**Comment by ghost** [comment]
Awesome, thank you so much.
