### ISSUE TITLE
Is there any more documentation on this?

### ISSUE THREAD

**Issue by dodriscoll** [calvinmetcalf/leaflet.shapefile#28]
Hi There,
Not so much an issue as a plea for help! I have the plugin working to pull in a .zip shapefile onto a website.  I would like to be able to run it as it runs in the demo where the user can upload their own file to overlay their data on my map.  Is this possible to do?  

Any advice on how to go about implementing this would be great.  I have a box where the user can browse to a file and select it but I'm not too sure what happens then, can I just pass that file to the new L.Shapefile(uploadedfile) in some way?

Many thanks,

**Comment by knownasilya** [comment]
The code for the demo is located here https://github.com/calvinmetcalf/leaflet.shapefile/blob/gh-pages/index.html#L42
See if that helps you.

**Comment by dodriscoll** [comment]
Thanks yes I can work it as it is here where the file name 'congress.zip' is located within the same folder as the site itself.  I would like to know how to use it in the same way as the demo http://leaflet.calvinmetcalf.com/ where you can click on a button or drag and drop a zipped shapefile from my machine onto the map. 

I've created a field with input type file which allows me to browse to the files on my computer but I'm a little unclear as to what happens after this.

Do I need to create a temporary folder on the sever where the data is loaded into and then add it to the map from there using the L.Shapefile.  Or does the code render the zipped shapefile on the client side (as I assumed it did!) and therefore you just need the file path?

Apologies for all the questions I'm not a trained programmer as you may have guessed!

**Comment by knownasilya** [comment]
Ah yes that example would be here: http://leaflet.calvinmetcalf.com/script.js and the relevant code is in the `handleFile` function, which sets the data on the worker, and then the worker does some topojson processing (worker defined towards the top), and returns the data in the `setWorkerEvents` function, and adds it as a layer to the map.

It's pretty involved, so feel free to ask questions once you have tried something and have run into specific issue :smile:

**Comment by dodriscoll** [comment]
Thanks for your help I've made some progress!  One error I'm getting which I can't figure out is "NetworkError: 404 Not Found - http://localhost/addShapefileTest/jam/catiline/dist/catiline.js"

I've referenced the catiline.js file (in a folder called dist) but don't have any folder called jam/catiline etc.  does the catiline.js file need to be in a specifically named location?

**Comment by calvinmetcalf** [comment]
it does if you copied http://leaflet.calvinmetcalf.com/script.js then yes because that was where it was located on that site.

**Comment by dodriscoll** [comment]
Hi There,
I am getting an error now from the setWorkerEvents() function in the script.js. It doesn't really give much information other than error!I've edited my layer control to be called var lc but there is something in the lc.addOverlay (l.geoJson....) line 124 of script.js that it doesn't like.  

This error appears before I click the button to load the file.  If I go ahead and click the button to load the file nothing happens the spinner just keeps spinning...any ideas or thoughts on what might cause this greatly appreciated.

**Comment by calvinmetcalf** [comment]
can you post your code in question somewhere like https://gist.github.com or http://jsbin.com?

**Comment by dodriscoll** [comment]
I've created a gist with 3 of the files in use these are:

> the leaflet.shpfile - only change from your leaflet.shpfile is the importUrl at the top, not sure if this should be changed? 
> the mapLayers.js - which is my mapSetup file so have copied and pasted code from the mapSetup.js script in here
> script.js again this is largely the same as your script.js only difference is  my map is called 'map' as opposed to 'm' so I've replaced m where necessary 

https://gist.github.com/dodriscoll/4a96f825ebe8123070b4

**Comment by calvinmetcalf** [comment]
so on [line 124](https://gist.github.com/dodriscoll/4a96f825ebe8123070b4#file-script-js-L124) this is where it tries to add the layer onto the map, if if there isn't something there you could have some problems,

**Comment by dodriscoll** [comment]
thanks Calvin yes I understood that this is where it's trying to add the layer but I have tested with the same zip files that I tested on your demo site so there is definitely data in the zipped shapefile. The error appears when the page loads before I even click the button to upload a file which is a bit confusing.  Also I'm wondering could it be an issue with the security?  I'm testing it using a IIS on my local machine?

**Comment by calvinmetcalf** [comment]
You are probably better off extracting the drag and drop code and then
combining it with the shapefile-js code.

**Comment by ahalota** [comment]
I'm having a bit of a hard time following your demo as well. I think the trouble is that your demo uses many more features than needed to show how it works, so it's hard to understand if you are unfamiliar with things such as the various calls to 'require', importscripts, jam, colorbrewer, topojson, etc... 

I have been trying to figure it out by copying your entire example and slowly removing bits of code as I realize what they do and whether or not I need them. It's tricky to see where your code links in to the two libraries you say are needed for it.

It would be really helpful if you could add a simple pared down example.

**Comment by calvinmetcalf** [comment]
so there is [this demo](https://github.com/calvinmetcalf/leaflet.shapefile/blob/21dde120cf11071e2193d22bfb7983202b7856ea/index.html) which shows just what is needed to get a shpfile onto the map

**Comment by ahalota** [comment]
Ah, I missed that.

In that case, my follow-up question might not be so closely related to the plugin. The demo you made with the file uploader is great and I'm hoping to emulate that (I tihnk many searches for using your plugin show others like it as well), but am not familiar with many of the libraries and the require/importscripts format used in that code. Could you create a simplified version of the file upload demo that is easier to follow along?

**Comment by calvinmetcalf** [comment]
drag and drop is kinda outside the scope of this library...https://github.com/bevacqua/dragula might be something to look into to making easier stuff for drag and drop

**Comment by ahalota** [comment]
Oh, I hadn't even noticed the drag and drop. I was just trying to get as far as uploading a file with the file upload window and then adding the shapefile to my map. That's probably why I was getting lost in the demo, it has a lot of lovely extra features but it's hard to decouple if you aren't familiar with it. Especially with catiline I think I was getting lost, but your instructions mention that it is required to use the library sometimes?

**Comment by calvinmetcalf** [comment]
ok so https://developer.mozilla.org/en-US/docs/Web/API/FileReader is what you use to get the stuff as an arraybuffer, and you can then add that to shpjs

**Comment by ahalota** [comment]
Ok, I'm trying to put together a simple demo once I figure this out that will hopefully help others in my situation as well.

For just a file upload and adding it to the map, do I need the catiline.js?

**Comment by calvinmetcalf** [comment]
nope cataline is optional just for making things faster, If you open a pull request to add the demo to this repo I can give you some pointers [here](https://github.com/calvinmetcalf/leaflet.workspace/blob/09f1025825e0d76036e9d524e481b09b6c7398db/script.js#L73-L200) is generally where the button stuff is being done though [this line](https://github.com/calvinmetcalf/leaflet.workspace/blob/09f1025825e0d76036e9d524e481b09b6c7398db/script.js#L97) would need to be changed to just add the shapefile layer since we aren't using a worker and you wouldn't need [this part](https://github.com/calvinmetcalf/leaflet.workspace/blob/09f1025825e0d76036e9d524e481b09b6c7398db/script.js#L121-L129)

**Comment by ahalota** [comment]
A simple .zip file upload demo: http://jsfiddle.net/ashalota/ov0p4ajh/10/ .
 I also added a pull request for this same file.

**Comment by sebsti34** [comment]
hi,

i would like to create the same page : http://leaflet.calvinmetcalf.com/#3/32.69/10.55

but it doesn't work
the drag button is not here.
could you help me please?

**Comment by calvinmetcalf** [comment]
@sebsti34 that's located [here](https://github.com/calvinmetcalf/leaflet.workspace)

**Comment by sebsti34** [comment]
thank you very much @calvinmetcalf ! 
I will be able to have fun!

**Comment by sebsti34** [comment]
Hi,

So now it works properly.
I would also like to be able to display shp.zip which are already stored on my server in a folder and whose list of files is displayed in a drop-down list next to the map. The drop-down list appears correctly with the name of my files but I can not make the link so that the shp appear on the map when the user selects one of the files. Is it possible with an adaptation of your script to achieve this?

**Comment by calvinmetcalf** [comment]
it depends a lot on how things are actually set up, but one thing is that you can pass a url to this library and if it ends in .zip it will download a zipfile from that address, otherwise it will append `.shp`, `.dbf` etc to the end of the file and try to download all of the files separately

**Comment by sebsti34** [comment]
I do not understand or I have not explained myself well. I do not wish to url. the .zip containing my shp will be on the server (it's me who would put them) and the user will be able to choose in a drop-down list the shp he wants to display on the map.
I created the dropdown list but when I make a choice the .zip will download to the places to display on the map. I can not make the link for that

**Comment by lucasscazzariello** [comment]
Hello! I try to import catiline and leaftlet.shpfile but when I load the app I get this error

```
catiline.js?af64:95 Uncaught TypeError: global.attachEvent is not a function
    at eval (catiline.js?af64:95)
    at eval (catiline.js?af64:107)
    at eval (catiline.js?af64:769)
    at Object../src/assets/js/catiline.js (app.js:8957)
    at __webpack_require__ (app.js:833)
    at fn (app.js:130)
    at eval (main.js?56d7:1)
    at Module../src/main.js (app.js:9053)
    at __webpack_require__ (app.js:833)
    at fn (app.js:130)
```

help me please
