### ISSUE TITLE
index.html example doesn't work

### ISSUE THREAD

**Issue by sclaresmt** [calvinmetcalf/leaflet.shapefile#30]
Hi first of all, thanks for sharing.

I'm trying to include leaflet.shapefile in my project firstly in the simplest way following the "index.html" example. I don't know even if it was intended to be an example, but if so, I noticed that it isn't working. It only shows base tile layer, the "watercolor" one, and it isn't adding to the map the "congress.zip" file because it can't find any feature in it.

Maybe I'm doing something wrong, in that case i would to ask for some help.

Thank you in advance.

**Comment by calvinmetcalf** [comment]
http://calvinmetcalf.github.io/leaflet.shapefile/ is based on that file and it works for me

**Comment by sclaresmt** [comment]
I donwloaded all files and decompressed them, then i opened index with Chrome. It saids "Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource". I've got my aswer, my apologies. I need to upload the file before using it.

Thank you.
