### ISSUE TITLE
Local Shapefile Styling

### ISSUE THREAD

**Issue by jaysmith1987** [calvinmetcalf/leaflet.shapefile#33]
Hello Calvin,

I was able to recreate your local zipfile example in my application unfortunately I was unable to get the program to read the properties of the shapefile. In the info window for the shapefile it shows a color code but only black dots show up for shapefiles. If possible can you point me to where in your script the feature style is loaded I am guessing one of my files that is associated in the require.js is incorrect but I am not sure which file is causing this.

**Comment by calvinmetcalf** [comment]
https://github.com/calvinmetcalf/leaflet.workspace/blob/09f1025825e0d76036e9d524e481b09b6c7398db/script.js#L29, it's likely your missing stuff from this folder https://github.com/calvinmetcalf/leaflet.workspace/tree/09f1025825e0d76036e9d524e481b09b6c7398db/js

**Comment by boniyustin** [comment]
is it possible to have this coloring on L.Shapefile not Leaflet.workspace?

**Comment by calvinmetcalf** [comment]
@boniyustin you are free to add it to any app you made with L.Shapefile
