### ISSUE TITLE
max layer number 

### ISSUE THREAD

**Issue by rakucmr** [calvinmetcalf/leaflet.shapefile#4]
In IE and Firefox not all layers are displayed. In Opera, Chrome is ok.
What is the problem?

<pre><code>

var map = L.map('map').setView([45.70, 25.50], 7);
// add an OpenStreetMap tile layer
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

var myStyle = {
"color": "#ff7800",
"weight": 1,
"opacity": 0.65
};

var myStyle2 = {
"color": "#0000FF",
"weight": 1,
"opacity": 0.65
};

var shpfile = new L.Shapefile('Satu-Mare.zip',{style: myStyle});
shpfile.addTo(map);
var shpfile2 = new L.Shapefile('Oradea.zip',{style: myStyle2});
shpfile2.addTo(map);
var shpfile3 = new L.Shapefile('Maramures.zip',{style: myStyle2});
shpfile3.addTo(map);
var shpfile4 = new L.Shapefile('Suceava.zip',{style: myStyle});
shpfile4.addTo(map);
var shpfile5 = new L.Shapefile('Botosani.zip',{style: myStyle2});
shpfile5.addTo(map);
var shpfile6 = new L.Shapefile('Salaj.zip',{style: myStyle});
shpfile6.addTo(map);
var shpfile7 = new L.Shapefile('Cluj.zip',{style: myStyle2});
shpfile7.addTo(map);
var shpfile8 = new L.Shapefile('Bistrita-Nasaud.zip',{style: myStyle});
shpfile8.addTo(map);
var shpfile9 = new L.Shapefile('Mures.zip',{style: myStyle2});
shpfile9.addTo(map);
var shpfile10 = new L.Shapefile('Harghita.zip',{style: myStyle});
shpfile10.addTo(map);
var shpfile11 = new L.Shapefile('Neamt.zip',{style: myStyle2});
shpfile11.addTo(map);
var shpfile12 = new L.Shapefile('Iasi.zip',{style: myStyle});
shpfile12.addTo(map);
var shpfile13 = new L.Shapefile('Arad.zip',{style: myStyle});
shpfile13.addTo(map);
var shpfile14 = new L.Shapefile('Timis.zip',{style: myStyle2});
shpfile14.addTo(map);
var shpfile15 = new L.Shapefile('Caras-Severin.zip',{style: myStyle});
shpfile15.addTo(map);
var shpfile16 = new L.Shapefile('Mehedinti.zip',{style: myStyle2});
shpfile16.addTo(map);
var shpfile17 = new L.Shapefile('Hunedoara.zip',{style: myStyle});
shpfile17.addTo(map);
var shpfile18 = new L.Shapefile('Gorj.zip',{style: myStyle2});
shpfile18.addTo(map);
var shpfile19 = new L.Shapefile('Dolj.zip',{style: myStyle});
shpfile19.addTo(map);
var shpfile20 = new L.Shapefile('Alba.zip',{style: myStyle2});
shpfile20.addTo(map);
var shpfile21 = new L.Shapefile('Vaslui.zip',{style: myStyle2});
shpfile21.addTo(map);
var shpfile22 = new L.Shapefile('Galati.zip',{style: myStyle});
shpfile22.addTo(map);
var shpfile23 = new L.Shapefile('Tulcea.zip',{style: myStyle2});
shpfile23.addTo(map);
var shpfile24 = new L.Shapefile('Constanta.zip',{style: myStyle});
shpfile24.addTo(map);
var shpfile26 = new L.Shapefile('Olt.zip',{style: myStyle});
shpfile26.addTo(map);
var shpfile25 = new L.Shapefile('Calarasi.zip',{style: myStyle2});
shpfile25.addTo(map);
var shpfile28 = new L.Shapefile('Giurgiu.zip',{style: myStyle});
shpfile28.addTo(map);
var shpfile27 = new L.Shapefile('Teleorman.zip',{style: myStyle2});
shpfile27.addTo(map);
var shpfile29 = new L.Shapefile('Valcea.zip',{style: myStyle2});
shpfile29.addTo(map);
var shpfile30 = new L.Shapefile('Sibiu.zip',{style: myStyle});
shpfile30.addTo(map);
var shpfile31 = new L.Shapefile('Brasov.zip',{style: myStyle2});
shpfile31.addTo(map);
var shpfile32 = new L.Shapefile('Arges.zip',{style: myStyle});
shpfile32.addTo(map);
var shpfile33 = new L.Shapefile('Dambovita.zip',{style: myStyle2});
shpfile33.addTo(map);
var shpfile34 = new L.Shapefile('Prahova.zip',{style: myStyle});
shpfile34.addTo(map);
var shpfile35 = new L.Shapefile('Ilfov.zip',{style: myStyle2});
shpfile35.addTo(map);
var shpfile36 = new L.Shapefile('Bucuresti.zip',{style: myStyle});
shpfile36.addTo(map);
var shpfile37 = new L.Shapefile('Covasna.zip',{style: myStyle2});
shpfile37.addTo(map);
var shpfile38 = new L.Shapefile('Bacau.zip',{style: myStyle});
shpfile38.addTo(map);
var shpfile39 = new L.Shapefile('Vrancea.zip',{style: myStyle2});
shpfile39.addTo(map);
var shpfile40 = new L.Shapefile('Buzau.zip',{style: myStyle});
shpfile40.addTo(map);
var shpfile41 = new L.Shapefile('Ialomita.zip',{style: myStyle2});
shpfile41.addTo(map);
var shpfile42 = new L.Shapefile('Braila.zip',{style: myStyle});
shpfile42.addTo(map);

</code></pre>

**Comment by calvinmetcalf** [comment]
are you getting any errors in your console?

**Comment by rakucmr** [comment]
no error

**Comment by calvinmetcalf** [comment]
can you post an example ?

On Fri, May 23, 2014 at 7:32 AM, Razvan notifications@github.com wrote:

> no error
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/calvinmetcalf/leaflet.shapefile/issues/4#issuecomment-43998493
> .

## 

-Calvin W. Metcalf

**Comment by rakucmr** [comment]
check it here: http://maimultaviteza.ro/test/

**Comment by calvinmetcalf** [comment]
try the close-worker branch

**Comment by rakucmr** [comment]
now is ok, thanks!
