### ISSUE TITLE
can't make it work 

### ISSUE THREAD

**Issue by fitoprincipe** [calvinmetcalf/leaflet.shapefile#40]
Hello, I want to make use of the library because I have a very large geoJSON file (too many nodes) and when I try to use it in my site (hosted in a free server by the way), it just takes too long. I think this plugin could solve that. I am trying to implement the shp.js created by Mano Marks as it does this site: https://www.e-education.psu.edu/geog863/l5_p3.html, but I made it work only for point files.
To start using your library I just downloaded the demo html, the libraries (directly from the demo), and also the congress.zip. But when I open (locally) on my browser, it just doesn't load the shapefile.. if I can't make that work I just can't continue. (I am not even close to a programmer, I have only basic knowladge). Thank you.

**Comment by calvinmetcalf** [comment]
this library just turns it into a geojson file so it would probably take
even longer using this as opposed ot using straight geojson.

**Comment by fitoprincipe** [comment]
Thank you, that is what I wanted to hear, I was almost sure of that, but I needed to confirm. What made me confuse is that the shp.js is over 10K lines! I thought 'there is a hard work'.. both js files made by Marks are about 130 lines. Thank you!
