### ISSUE TITLE
shpfile's encode type is BIG5

### ISSUE THREAD

**Issue by Chadjhou** [calvinmetcalf/leaflet.shapefile#42]
HI, im chinese engineer in Taiwan 
i try this example use the shapefile zip 
and i found this case cant write chinese ,
can u teach me where can i fix this problem 
thx!

**Comment by calvinmetcalf** [comment]
this is related to calvinmetcalf/parseDBF#9 which I need to figure out how to do in a way that doesn't explode the library size

**Comment by Chadjhou** [comment]
hi   i prove this problem use the function
'function Decodeuint8arr(uint8array) {
        return new TextDecoder("big5").decode(uint8array);
    }'
i put this function to "function:rowfuncs " !!

**Comment by calvinmetcalf** [comment]
an example of a chinese shapefile would be very helpful when writing tests
