### ISSUE TITLE
Problem loading shape file with roads

### ISSUE THREAD

**Issue by vertigo7x** [calvinmetcalf/leaflet.shapefile#44]
Hi, first of all, thanks for your plugin. It does a great job with all the shape files I've tried, except the ones that have roads (lines) in them. The curious thing is if I load the shapefile on your demo page, the lines show up fine, but I've cloned your repo and modified the index to load my road shape files on the map and they wont get drawn. I'm a newbie on maps and cartography and dealing with projections and positions its getting my nuts.
Thanks for your advice.

**Comment by calvinmetcalf** [comment]
are you just opening up the file directly on the file system? (aka it says file:// in the browser address file) if so that's your problem, you need to run some sort of server locally (if you have node you can do `npm install -g serve`

**Comment by vertigo7x** [comment]
Hi Calvin,
I'm using two different servers, one for testing (a node server) and a Tomcat 7.0 that would serve the zips with the shape files. Inspecting the JS events, on your demo, the features get loaded from the shapefile and then get created in the map overlay svg node, but with the code from the repo, the file get loaded but no child nodes get created.

**Comment by calvinmetcalf** [comment]
ok first try commenting out [this line](https://github.com/calvinmetcalf/leaflet.shapefile/blob/21dde120cf11071e2193d22bfb7983202b7856ea/index.html#L39) in the html, then run it and see if any errors show up in the console.

then if still nothing try uploading the file to http://leaflet.calvinmetcalf.com/ and see if it works, if not then there may be something unsupported in the file.

also how big is the zipfile?

**Comment by vertigo7x** [comment]
Hi Calvin,
Commenting out the catiline.js does the job. In the demo, I also have to include explicily the shp.js library and the shape file loads perfectly. Also, you asked about the size of the shapefile, well, it is around 5Mb, not the biggest I have.

Thanks for your advice!
