### ISSUE TITLE
polygon shapefile not loading

### ISSUE THREAD

**Issue by aolufisayo** [calvinmetcalf/leaflet.shapefile#48]
I'm unable to load my project shapefile on the webmap. Using the 'councils' example it works fine and I can see the 'finished loaded shapefile' message on console but taking a look at my shapefile console, there are no messages at all. I already verified the shapefile is in EPSG:4326. Please,help me out.

**Comment by calvinmetcalf** [comment]
can you post some example code ? maybe fork this repo and put your shapefile in place of the demo

**Comment by holuphisayor** [comment]
Thanks for your time. I have been able to figure out the problem and it has been resolved. Your comment on uploading a copy of my shapefile prompted me to check my zipped file properties. I discovered it was in .rar format while I was calling .zip in the code. I changed it from .rar to .zip and it now works.

**Comment by aolufisayo** [comment]
Thanks for your time. I have been able to figure out the problem and it has been resolved. Your comment on uploading a copy of my shapefile prompted me to check my zipped file properties. I discovered it was in .rar format while I was calling .zip in the code. I changed it from .rar to .zip and it now works.
